# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm_left
  joint_model_group_pose: home_left
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - pan_tilt_yaw_joint
    - pan_tilt_pitch_joint
    - left_arm_joint_1
    - left_arm_joint_2
    - left_arm_joint_3
    - left_arm_joint_4
    - left_arm_joint_5
    - left_arm_joint_6
    - left_arm_joint_finger_1
    - left_arm_joint_finger_tip_1
    - left_arm_joint_finger_2
    - left_arm_joint_finger_tip_2
    - right_arm_joint_1
    - right_arm_joint_2
    - right_arm_joint_3
    - right_arm_joint_4
    - right_arm_joint_5
    - right_arm_joint_6
    - right_arm_joint_finger_1
    - right_arm_joint_finger_tip_1
    - right_arm_joint_finger_2
    - right_arm_joint_finger_tip_2
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: arm_left_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - left_arm_joint_1
      - left_arm_joint_2
      - left_arm_joint_3
      - left_arm_joint_4
      - left_arm_joint_5
      - left_arm_joint_6
  - name: arm_right_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - right_arm_joint_1
      - right_arm_joint_2
      - right_arm_joint_3
      - right_arm_joint_4
      - right_arm_joint_5
      - right_arm_joint_6
  - name: gripper_left_controller
    action_ns: gripper_command
    default: True
    type: GripperCommand
    joints:
      - left_arm_joint_finger_1
      - left_arm_joint_finger_2
  - name: gripper_right_controller
    action_ns: gripper_command
    default: True
    type: GripperCommand
    joints:
      - left_arm_joint_finger_1
      - left_arm_joint_finger_2